name = "genrec"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["GenRec"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
weak.linter.style.header = false
weak.linter.style.longLine = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.2"

[[lean_lib]]
name = "GenRec"
